increase wait

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -130,7 +130,7 @@ jobs:
           ls -l "./$verify_script" || echo "Script not found"
           file "./$verify_script" || echo "Could not determine file type"
           [[ ! -x "./$verify_script" ]] && echo "Script is not executable"
-          head -n 1 "./$verify_script" || echo "Failed to read script"
+          head -n 10 "./$verify_script" || echo "Failed to read script"
 
           echo "initial status"
           echo $initial_status
