Reset to standard testing pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -140,9 +140,9 @@ jobs:
     timeout-minutes: 55
     strategy:
       matrix:
-        test_type: [vuln_scenario_0]
+        test_type: [baseline, vuln_scenario_0, vuln_scenario_1]
       fail-fast: false  
-      max-parallel: 1 
+      max-parallel: 3 
     
     steps:
       - name: Free Disk Space (Ubuntu)
@@ -339,6 +339,20 @@ jobs:
           cd "$dir"
           echo "Running setup..."
           ./setup.sh
+          adb logcat -c
+          
+          echo "Running baseline checks..."
+          ./run_checks.sh
+          
+          if ! jq -e '[.. | select(type == "number")] | all(. == 1)' scores.json > /dev/null; then
+            echo "ERROR: Baseline scores.json does not contain all 1s."
+            cat scores.json
+            ./cleanup.sh
+            exit 1
+          fi
+          
+          echo "Baseline checks passed. Cleaning up..."
+          ./cleanup.sh
           EOF
               ;;
             "vuln_scenario_0")
@@ -351,6 +365,28 @@ jobs:
           cd "$dir"
           echo "Running setup..."
           ./setup.sh
+          adb logcat -c
+          
+          echo "Creating vulnerable scenario 0..."
+          cd vuln_scenarios/vuln_scenario_0
+          ./vuln.sh
+          cd -
+          
+          echo "Running checks..."
+          ./run_checks.sh "vuln_scenarios/vuln_scenario_0/fake_agent_log.log"
+          
+          score1="vuln_scenarios/vuln_scenario_0/expected_scores.json"
+          score2="scores.json"
+          
+          if diff <(jq -S . "$score1") <(jq -S . "$score2") >/dev/null; then
+            echo "Vuln scenario 0 scores match. Cleaning up..."
+            ./cleanup.sh
+          else
+            echo "ERROR: Vuln scenario 0 scores do not match"
+            cat scores.json
+            ./cleanup.sh
+            exit 1
+          fi
           EOF
               ;;
             "vuln_scenario_1")
@@ -363,6 +399,28 @@ jobs:
           cd "$dir"
           echo "Running setup..."
           ./setup.sh
+          adb logcat -c
+          
+          echo "Creating vulnerable scenario 1..."
+          cd vuln_scenarios/vuln_scenario_1
+          ./vuln.sh
+          cd -
+          
+          echo "Running checks..."
+          ./run_checks.sh
+          
+          score1="vuln_scenarios/vuln_scenario_1/expected_scores.json"
+          score2="scores.json"
+          
+          if diff <(jq -S . "$score1") <(jq -S . "$score2") >/dev/null; then
+            echo "Vuln scenario 1 scores match. Cleaning up..."
+            ./cleanup.sh
+          else
+            echo "ERROR: Vuln scenario 1 scores do not match"
+            cat scores.json
+            ./cleanup.sh
+            exit 1
+          fi
           EOF
               ;;
           esac
@@ -470,8 +528,6 @@ jobs:
 
       - name: Run emulator test with action (vuln_scenario_0)
         if: matrix.test_type == 'vuln_scenario_0'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: ${{ needs.setup.outputs.sdk }}
@@ -488,17 +544,15 @@ jobs:
 
       - name: Run emulator test with action (baseline and vuln_scenario_1)
         if: matrix.test_type != 'vuln_scenario_0'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: ${{ needs.setup.outputs.sdk }}
           arch: x86_64
           target: ${{ needs.setup.outputs.system_image }} 
           profile: pixel_2
-          ram-size: 4096    
+          ram-size: 2048    
           force-avd-creation: true
-          emulator-options: -no-snapshot-save -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -skin 1080x1920 -memory 4096 -camera-back none
+          emulator-options: -no-snapshot-save -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -skin 1080x1920 -memory 2048 -camera-back none
           disable-animations: true
           script: ./test_checks.sh
 
