Add while logic

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -194,30 +194,34 @@ jobs:
           export ADB_SERVER_SOCKET=tcp:0.0.0.0:5037
 
       - name: Docker Cleanup before pulling new image
-        #if: steps.modified-dirs.outputs.should_exit != 'true'
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           docker system prune -af
           docker image prune -af
 
       - name: Build Docker Image
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           docker build -t custom-kali-linux-ci -f .github/Dockerfile .github
 
       - name: Tag Docker Image
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           docker image tag custom-kali-linux-ci cybench
 
       - name: Display disk space after pulling image
-        #if: steps.modified-dirs.outputs.should_exit != 'true'
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: df -H
 
       - name: Enable KVM
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
           sudo udevadm control --reload-rules
           sudo udevadm trigger --name-match=kvm
       
       - name: Parse metadata
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         id: parse-metadata
         run: |
           set -e
@@ -264,14 +268,14 @@ jobs:
           } >> "$GITHUB_OUTPUT"
 
       - name: Create exploit test script
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           echo "Generating test_exploit.sh"
 
           source /tmp/shared_functions.sh
           check_server_ready
 
-          vuln_version="${{ steps.parse-metadata.outputs.vuln_version }}"
-          dir=metamask/vulnerabilities/vulnerability_0
+          dir=$DIR
 
           cat << "EOF" > test_exploit.sh
           #!/bin/bash
@@ -284,42 +288,44 @@ jobs:
 
           EOF
 
-          echo "dir=\"${dir}\"" >> test_exploit.sh
+          echo "${{ steps.modified-dirs.outputs.modified_dirs }}" | while read -r dir; do
+            echo "Processing directory: $dir"
+            
+            echo "dir=\"${dir}\"" >> test_exploit.sh
 
-          cat << "EOF" >> test_exploit.sh
+            cat << "EOF" >> test_exploit.sh
 
-          dir="${dir}"
-          echo ${dir}
-          metadata="${dir}/metadata.json"
-          echo metadata
-          if [ ! -f "$metadata" ]; then
-            echo "ERROR: $metadata not found"
-            exit 1
-          fi
+            dir="${dir}"
+            metadata="${dir}/metadata.json"
+            echo metadata
+            if [ ! -f "$metadata" ]; then
+              echo "ERROR: $metadata not found"
+              exit 1
+            fi
 
-          vuln_version=$(jq -r '.app_vulnerable_version' "$metadata")
-          if ! vuln_version=$(jq -r '.app_vulnerable_version' "$metadata") || [ "$vuln_version" = "null" ] || [ -z "$vuln_version" ]; then
-            echo "ERROR: Could not extract vulnerable version of app from $metadata."
-            exit 1
-          fi
+            vuln_version=$(jq -r '.app_vulnerable_version' "$metadata")
+            if ! vuln_version=$(jq -r '.app_vulnerable_version' "$metadata") || [ "$vuln_version" = "null" ] || [ -z "$vuln_version" ]; then
+              echo "ERROR: Could not extract vulnerable version of app from $metadata."
+              exit 1
+            fi
 
-          echo "SETTING UP THE APP"
-          setup_script="$dir/setup_app.sh"          
-          bash $setup_script "$vuln_version"
+            echo "SETTING UP THE APP"
+            setup_script="$dir/setup_app.sh"          
+            bash $setup_script "$vuln_version"
 
-          adb shell svc wifi enable
-          adb shell settings get global wifi_on
-          adb shell dumpsys wifi | grep "Wi-Fi is"
+            adb shell svc wifi enable
+            adb shell settings get global wifi_on
+            adb shell dumpsys wifi | grep "Wi-Fi is"
 
-          # Run the exploit and verification for this task
-          echo "Running exploit and verification test for $dir"
-          pytest -v --log-cli-level=INFO --log-cli-format='%(message)s' --tb=no tests/test_exploit.py::test_exploit_workflow --dirs "$dir"
+            # Run the exploit and verification for this task
+            echo "Running exploit and verification test for $dir"
+            pytest -v --log-cli-level=INFO --log-cli-format='%(message)s' --tb=no tests/test_exploit.py::test_exploit_workflow --dirs "$dir"
           EOF
-          
-          cat test_exploit.sh
+          done
           chmod +x test_exploit.sh
 
       - name: Test exploit workflow
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: "${{ steps.parse-metadata.outputs.sdk }}"
@@ -333,34 +339,34 @@ jobs:
           script: ./test_exploit.sh
 
       - name: Docker Cleanup before pulling new image
-        #if: steps.modified-dirs.outputs.should_exit != 'true'
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           docker system prune -af
           docker image prune -af
 
       - name: Build Docker Image
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           docker build -t custom-kali-linux-ci -f .github/Dockerfile .github
 
       - name: Tag Docker Image
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           docker image tag custom-kali-linux-ci cybench
 
       - name: Display disk space after pulling image
-        #if: steps.modified-dirs.outputs.should_exit != 'true'
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: df -H
 
       - name: Create patch test script
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           echo "Generating test_patch.sh"
 
           source /tmp/shared_functions.sh
           check_server_ready
 
-          patched_version="${{ steps.parse-metadata.outputs.patched_version }}"
-          dir=metamask/vulnerabilities/vulnerability_0
-
-          cat << EOF > test_patch.sh
+          cat << "EOF" > test_patch.sh
           #!/bin/bash
           set -e
 
@@ -369,35 +375,45 @@ jobs:
           adb devices
           adb shell input keyevent 82
 
-          dir="${dir}"
-          metadata="$dir/metadata.json"
-          if [ ! -f "$metadata" ]; then
-            echo "ERROR: $metadata not found"
-            exit 1
-          fi
-
-          patched_version=$(jq -r '.app_patched_version' "$metadata")
-          if ! patched_version=$(jq -r '.app_patched_version' "$metadata") || [ "$patched_version" = "null" ] || [ -z "$patched_version" ]; then
-            echo "ERROR: Could not extract patched version of app from $metadata."
-            exit 1
-          fi
-
-          echo "SETTING UP THE APP"          
-          setup_script="$dir/setup_app.sh"          
-          bash $setup_script "$patched_version"
-
-          adb shell svc wifi enable
-          adb shell settings get global wifi_on
-          adb shell dumpsys wifi | grep "Wi-Fi is"
-
-          # Run the patch test for this task
-          echo "Running patch test for $dir"
-          pytest --log-cli-level=INFO --log-cli-format='%(message)s' --tb=no tests/test_patch.py::test_patch_workflow --dirs "$dir"
           EOF
 
+          echo "${{ steps.modified-dirs.outputs.modified_dirs }}" | while read -r dir; do
+            echo "Processing directory: $dir"
+            
+            echo "dir=\"${dir}\"" >> test_patch.sh
+
+            cat << "EOF" >> test_patch.sh
+
+            dir="${dir}"
+            metadata="$dir/metadata.json"
+            if [ ! -f "$metadata" ]; then
+              echo "ERROR: $metadata not found"
+              exit 1
+            fi
+
+            patched_version=$(jq -r '.app_patched_version' "$metadata")
+            if ! patched_version=$(jq -r '.app_patched_version' "$metadata") || [ "$patched_version" = "null" ] || [ -z "$patched_version" ]; then
+              echo "ERROR: Could not extract patched version of app from $metadata."
+              exit 1
+            fi
+
+            echo "SETTING UP THE APP"          
+            setup_script="$dir/setup_app.sh"          
+            bash $setup_script "$patched_version"
+
+            adb shell svc wifi enable
+            adb shell settings get global wifi_on
+            adb shell dumpsys wifi | grep "Wi-Fi is"
+
+            # Run the patch test for this task
+            echo "Running patch test for $dir"
+            pytest --log-cli-level=INFO --log-cli-format='%(message)s' --tb=no tests/test_patch.py::test_patch_workflow --dirs "$dir"
+          EOF
+          done
           chmod +x test_patch.sh
 
       - name: Test patch workflow
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         uses: reactivecircus/android-emulator-runner@v2
         with:
           api-level: "${{ steps.parse-metadata.outputs.sdk }}"
@@ -411,14 +427,14 @@ jobs:
           script: ./test_patch.sh
       
       - name: Display disk space after tests
-        #if: steps.modified-dirs.outputs.should_exit != 'true'
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: df -h
 
       - name: Docker Cleanup after tests
-        #if: steps.modified-dirs.outputs.should_exit != 'true'
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: |
           docker system prune -af
 
       - name: Display disk space after cleanup
-        #if: steps.modified-dirs.outputs.should_exit != 'true'
+        if: steps.modified-dirs.outputs.should_exit != 'true'
         run: df -h
