Add system_ui_watchdog

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -280,6 +280,61 @@ jobs:
             fi
           }
 
+          system_ui_watchdog() {
+            echo "Starting System UI watchdog..."
+            EMU_BOOTED=0
+            first_launcher=1
+            n=0
+            while [[ $EMU_BOOTED = 0 ]]; do
+                CURRENT_FOCUS=$(adb shell dumpsys window 2>/dev/null | grep -i mCurrentFocus)
+                echo "Current focus: ${CURRENT_FOCUS}"
+
+                case $CURRENT_FOCUS in
+                "Launcher")
+                    if [[ $first_launcher == 1 ]]; then
+                    echo "Launcher detected, waiting 10 sec in case of popups..."
+                    sleep 10
+                    first_launcher=0
+                    else
+                    echo "Launcher stable, boot complete."
+                    EMU_BOOTED=1
+                    fi
+                    ;;
+                "Not Responding: com.android.systemui")
+                    echo "Dismissing System UI popup..."
+                    adb shell input keyevent KEYCODE_ENTER
+                    adb shell input keyevent KEYCODE_DPAD_DOWN
+                    adb shell input keyevent KEYCODE_ENTER
+                    first_launcher=1
+                    ;;
+                "Not Responding: com.google.android.gms")
+                    echo "Dismissing GMS popup..."
+                    adb shell input keyevent KEYCODE_ENTER
+                    first_launcher=1
+                    ;;
+                "Not Responding: system")
+                    echo "Dismissing Process System popup..."
+                    adb shell input keyevent KEYCODE_ENTER
+                    first_launcher=1
+                    ;;
+                "ConversationListActivity")
+                    echo "Closing Messaging app..."
+                    adb shell input keyevent KEYCODE_ENTER
+                    first_launcher=1
+                    ;;
+                *)
+                    n=$((n + 1))
+                    echo "Waiting for Android to boot ($n)..."
+                    sleep 10
+                    if [ $n -gt 60 ]; then
+                    echo "Timeout: Emulator failed to boot in 10 minutes."
+                    exit 2
+                    fi
+                    ;;
+                esac
+            done
+          }
+
           start_emulator_logging() {
             echo "=== Starting emulator resource monitor ==="
             mkdir -p emulator_logs
@@ -647,6 +702,8 @@ jobs:
           adb wait-for-device
           REMOUNT_STATUS=$(adb shell mount | grep -E "(system|vendor|product)")
           echo "System mount status: $REMOUNT_STATUS"
+
+          system_ui_watchdog
 
           adb shell input keyevent 224
           echo "Emulator ready!"
