Add ability to change SDK using metadata.json

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,6 +54,14 @@ jobs:
             exit 1
           fi
 
+          sdk=$(jq -r '.sdk' $metadata)
+          if [ "$?" -ne 0 ] || [ "$sdk" = "null" ] || [ -z "$sdk" ]; then
+              echo "${ERROR} Could not extract SDK from $metadata. Use default (28)."
+              sdk=28
+          else 
+              echo "SDK: $sdk"
+          fi
+
           vuln_version=$(jq -r '.app_vulnerable_version' "$metadata")
           if ! vuln_version=$(jq -r '.app_vulnerable_version' "$metadata") || [ "$vuln_version" = "null" ] || [ -z "$vuln_version" ]; then
             echo "ERROR: Could not extract vulnerable version of app from $metadata."
@@ -90,6 +98,7 @@ jobs:
 
           # Export versions for use in subsequent steps
           {
+            echo "sdk=$sdk"
             echo "vuln_version=$vuln_version"
             echo "patched_version=$patched_version"
             echo "exploit_script=$exploit_script"
@@ -121,13 +130,14 @@ jobs:
           echo "Now in $(pwd)"
           cd "$DIR" || exit 1
           ls
-          echo "verify_script='$verify_script'"
-          ls -l "$verify_script"
           echo "Now in $(pwd)"
 
           vuln_version="${vuln_version}"
           verify_script="${verify_script}"
           exploit_script="${exploit_script}"
+
+          echo "$verify_script"
+          ls -l "$verify_script"
 
           echo "::group::SETTING UP THE APP"
           ./setup_app.sh "$vuln_version"
@@ -169,7 +179,7 @@ jobs:
       - name: Test Exploit Workflow
         uses: reactivecircus/android-emulator-runner@v2
         with:
-          api-level: 28
+          api-level: "${{ steps.parse-metadata.outputs.sdk }}"
           arch: x86_64
           target: google_apis
           profile: pixel_2
@@ -244,7 +254,7 @@ jobs:
       - name: Test Patch Workflow
         uses: reactivecircus/android-emulator-runner@v2
         with:
-          api-level: 28
+          api-level: "${{ steps.parse-metadata.outputs.sdk }}"
           arch: x86_64
           target: google_apis
           profile: pixel_2    
