test boot first w/out writable-system and then restart w

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -632,23 +632,13 @@ jobs:
           echo "PATH: $PATH"
           export PATH=$ANDROID_HOME/emulator:$PATH
           SDK_VERSION=${{ needs.setup.outputs.sdk }}
-          emulator -avd test_avd -writable-system -no-snapshot-load -no-snapshot-save -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -skin 1080x1920 -memory 4096 -camera-back none &
+
+          emulator -avd test_avd \
+            -no-snapshot-load -no-snapshot-save -wipe-data \
+            -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim \
+            -skin 1080x1920 -memory 4096 -camera-back none &
           adb wait-for-device
           check_emulator_boot
-
-          echo "Emulator booted successfully!"
-
-          # Wait for adbd to be ready
-          echo "Waiting for adbd to be ready..."
-          timeout=60
-          until adb shell "ls /system" &>/dev/null || [[ $timeout -le 0 ]]; do
-            sleep 1
-            ((timeout--))
-          done
-          if [[ "$timeout" -le 0 ]]; then
-            echo "adbd not ready in time."
-            exit 1
-          fi          
           
           adb root
           adb wait-for-device
@@ -658,29 +648,74 @@ jobs:
             adb wait-for-device
             check_emulator_boot
           fi
-          
-          adb root
-          timeout=30
-          until adb remount &>/dev/null || [[ $timeout -le 0 ]]; do
-            sleep 1
-            ((timeout--))
-          done
-          if [[ "$timeout" -le 0 ]]; then
-            echo "adb remount failed after waiting."
-            exit 1
-          fi
 
+          emulator -avd test_avd \
+            -writable-system -no-snapshot-load -no-snapshot-save \
+            -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim \
+            -skin 1080x1920 -memory 4096 -camera-back none &
           adb wait-for-device
-          REMOUNT_STATUS=$(adb shell mount | grep -E "(system|vendor|product)")
-          echo "System mount status: $REMOUNT_STATUS"
+          check_emulator_boot
 
-          echo "Disabling animations..."
+          adb root
+          adb remount
+          adb shell mount | grep system
+
           adb shell settings put global window_animation_scale 0
           adb shell settings put global transition_animation_scale 0
           adb shell settings put global animator_duration_scale 0
 
           adb shell input keyevent 224
           echo "Emulator ready!"
+
+          # emulator -avd test_avd -writable-system -no-snapshot-load -no-snapshot-save -wipe-data -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -skin 1080x1920 -memory 4096 -camera-back none &
+          # adb wait-for-device
+          # check_emulator_boot
+
+          # echo "Emulator booted successfully!"
+
+          # # Wait for adbd to be ready
+          # echo "Waiting for adbd to be ready..."
+          # timeout=60
+          # until adb shell "ls /system" &>/dev/null || [[ $timeout -le 0 ]]; do
+          #   sleep 1
+          #   ((timeout--))
+          # done
+          # if [[ "$timeout" -le 0 ]]; then
+          #   echo "adbd not ready in time."
+          #   exit 1
+          # fi          
+          
+          # adb root
+          # adb wait-for-device
+          # if [ "$SDK_VERSION" -gt 28 ]; then
+          #   adb shell avbctl disable-verification
+          #   adb reboot
+          #   adb wait-for-device
+          #   check_emulator_boot
+          # fi
+          
+          # adb root
+          # timeout=30
+          # until adb remount &>/dev/null || [[ $timeout -le 0 ]]; do
+          #   sleep 1
+          #   ((timeout--))
+          # done
+          # if [[ "$timeout" -le 0 ]]; then
+          #   echo "adb remount failed after waiting."
+          #   exit 1
+          # fi
+
+          # adb wait-for-device
+          # REMOUNT_STATUS=$(adb shell mount | grep -E "(system|vendor|product)")
+          # echo "System mount status: $REMOUNT_STATUS"
+
+          # echo "Disabling animations..."
+          # adb shell settings put global window_animation_scale 0
+          # adb shell settings put global transition_animation_scale 0
+          # adb shell settings put global animator_duration_scale 0
+
+          # adb shell input keyevent 224
+          # echo "Emulator ready!"
 
       - name: Run custom emulator test for vuln_scenario_0
         if: matrix.test_type == 'vuln_scenario_0'
